services:
  app:
    build:
      context: .
      target: dev
    working_dir: /app
    environment:
      - PORT=8080
    env_file:
      - .env
    command: /usr/local/bin/{{SOSO_APPNAME}}
    ports:
      - 8080:8080
    volumes:
      - $PWD:/app
      - {{SOSO_APPNAME}}-data:/app/data

volumes:
  {{SOSO_APPNAME}}-data:

